### ISSUE TITLE
Vulnerability issue on dependency log4j

### ISSUE THREAD

**Issue by richardsinelle** [ESAPI/esapi-java#9]
Hi

I use org.owasp.dependencycheck to check vulnerabilities on my project and esapi to filter all data provided by users.
Unfortunately, the owasp plugin shows a critical issue on log4j... coming for esapi module 

log4j-1.2.17.jar | cpe:2.3:a:apache:log4j:1.2.17:*:*:*:*:*:*:* | pkg:maven/log4j/log4j@1.2.17 | CRITICAL | 1 | Highest | 32
-- | -- | -- | -- | -- | -- | --

log4j with version 1.2.17 is very old and must be replace at least by  org.apache.logging.log4j » log4j-core or by org.slf4j:slf4j-api.

Could you please update the dependencies?

Thanks in advance

**Comment by kwwall** [comment]
ESAPI does not expose this vulnerability to users in an exploitable manner.
It is a false positive for us. I have written a security bulletin do
describe all the details and workarounds which I shall be uploading to our
"develop" branch shortly.

**Comment by xeno6696** [comment]
Also, this is against the wrong repository.  This is for the future ESAPI 3.X branch.  Issue should be applied against ESAPI/esapi-java-legacy

**Comment by kwwall** [comment]
Good point. I had been planning on creating a new GitHub issue to track this for the security bulletin that I was already in the process of writing up. I will do that and link to https://github.com/ESAPI/esapi-java/issues/9#issue-562048527

But since this CVE doesn't affect this 'esapi-java' repo, I am closing this issue.
